"""created tables

Revision ID: 8fc38a9e2d64
Revises: 
Create Date: 2023-11-24 20:42:15.729496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fc38a9e2d64'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('final_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(), nullable=True),
    sa.Column('question', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hidden_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('letter', sa.String(), nullable=True),
    sa.Column('theme', sa.String(), nullable=True),
    sa.Column('song1', sa.String(), nullable=True),
    sa.Column('song2', sa.String(), nullable=True),
    sa.Column('song3', sa.String(), nullable=True),
    sa.Column('song4', sa.String(), nullable=True),
    sa.Column('answer1', sa.String(), nullable=True),
    sa.Column('question1', sa.String(), nullable=True),
    sa.Column('answer2', sa.String(), nullable=True),
    sa.Column('question2', sa.String(), nullable=True),
    sa.Column('answer3', sa.String(), nullable=True),
    sa.Column('question3', sa.String(), nullable=True),
    sa.Column('answer4', sa.String(), nullable=True),
    sa.Column('question4', sa.String(), nullable=True),
    sa.Column('answer5', sa.String(), nullable=True),
    sa.Column('question5', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('theme', sa.String(), nullable=True),
    sa.Column('song1', sa.String(), nullable=True),
    sa.Column('answer1', sa.String(), nullable=True),
    sa.Column('question1', sa.String(), nullable=True),
    sa.Column('song2', sa.String(), nullable=True),
    sa.Column('answer2', sa.String(), nullable=True),
    sa.Column('question2', sa.String(), nullable=True),
    sa.Column('song3', sa.String(), nullable=True),
    sa.Column('answer3', sa.String(), nullable=True),
    sa.Column('question3', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trivia_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('letter', sa.String(), nullable=True),
    sa.Column('round', sa.String(), nullable=True),
    sa.Column('song', sa.String(), nullable=True),
    sa.Column('question', sa.String(), nullable=True),
    sa.Column('answer', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trivia_questions')
    op.drop_table('player_questions')
    op.drop_table('hidden_questions')
    op.drop_table('final_questions')
    # ### end Alembic commands ###
